export default defineEventHandler(() => {
  return gallery;
});

const gallery = [
  {
    tags: "tirthan",
    images: [
      "/images/tirthan/stay/1.webp",
      "/images/tirthan/stay/2.webp",
      "/images/tirthan/stay/3.webp",
      "/images/tirthan/stay/4.webp",
    ],
  },
  {
    tags: "kaziyar",
    images: [
      "/images/kaziyar/stay/1.webp",
      "/images/kaziyar/stay/10.webp",
      "/images/kaziyar/stay/11.webp",
      "/images/kaziyar/stay/12.webp",
      "/images/kaziyar/stay/13.webp",
      "/images/kaziyar/stay/14.webp",
      "/images/kaziyar/stay/15.webp",
      "/images/kaziyar/stay/16.webp",
      "/images/kaziyar/stay/2.webp",
      "/images/kaziyar/stay/3.webp",
      "/images/kaziyar/stay/4.webp",
      "/images/kaziyar/stay/5.webp",
      "/images/kaziyar/stay/6.webp",
      "/images/kaziyar/stay/7.webp",
      "/images/kaziyar/stay/8.webp",
      "/images/kaziyar/stay/9.webp",
    ],
  },
  {
    tags: "manali",
    images: [
      "/images/manali/stay/1.webp",
      "/images/manali/stay/10.webp",
      "/images/manali/stay/11.webp",
      "/images/manali/stay/12.webp",
      "/images/manali/stay/13.webp",
      "/images/manali/stay/14.webp",
      "/images/manali/stay/15.webp",
      "/images/manali/stay/16.webp",
      "/images/manali/stay/17.webp",
      "/images/manali/stay/18.webp",
      "/images/manali/stay/19.webp",
      "/images/manali/stay/2.webp",
      "/images/manali/stay/20.webp",
      "/images/manali/stay/21.webp",
      "/images/manali/stay/22.webp",
      "/images/manali/stay/23.webp",
      "/images/manali/stay/24.webp",
      "/images/manali/stay/25.webp",
      "/images/manali/stay/26.webp",
      "/images/manali/stay/27.webp",
      "/images/manali/stay/28.webp",
      "/images/manali/stay/29.webp",
      "/images/manali/stay/3.webp",
      "/images/manali/stay/30.webp",
      "/images/manali/stay/31.webp",
      "/images/manali/stay/32.webp",
      "/images/manali/stay/33.webp",
      "/images/manali/stay/34.webp",
      "/images/manali/stay/35.webp",
      "/images/manali/stay/36.webp",
      "/images/manali/stay/37.webp",
      "/images/manali/stay/38.webp",
      "/images/manali/stay/39.webp",
      "/images/manali/stay/4.webp",
      "/images/manali/stay/40.webp",
      "/images/manali/stay/41.webp",
      "/images/manali/stay/42.webp",
      "/images/manali/stay/43.webp",
      "/images/manali/stay/44.webp",
      "/images/manali/stay/45.webp",
      "/images/manali/stay/46.webp",
      "/images/manali/stay/47.webp",
      "/images/manali/stay/48.webp",
      "/images/manali/stay/49.webp",
      "/images/manali/stay/5.webp",
      "/images/manali/stay/50.webp",
      "/images/manali/stay/51.webp",
      "/images/manali/stay/6.webp",
      "/images/manali/stay/7.webp",
      "/images/manali/stay/8.webp",
      "/images/manali/stay/9.webp",
      "/images/manali/stay/rename.py",
    ],
  },
  {
    tags: "kasol",
    images: [
      "/images/kasol/stay/1.webp",
      "/images/kasol/stay/10.webp",
      "/images/kasol/stay/11.webp",
      "/images/kasol/stay/12.webp",
      "/images/kasol/stay/13.webp",
      "/images/kasol/stay/14.webp",
      "/images/kasol/stay/15.webp",
      "/images/kasol/stay/16.webp",
      "/images/kasol/stay/17.webp",
      "/images/kasol/stay/18.webp",
      "/images/kasol/stay/19.webp",
      "/images/kasol/stay/2.webp",
      "/images/kasol/stay/20.webp",
      "/images/kasol/stay/21.webp",
      "/images/kasol/stay/22.webp",
      "/images/kasol/stay/23.webp",
      "/images/kasol/stay/24.webp",
      "/images/kasol/stay/25.webp",
      "/images/kasol/stay/26.webp",
      "/images/kasol/stay/27.webp",
      "/images/kasol/stay/28.webp",
      "/images/kasol/stay/29.webp",
      "/images/kasol/stay/3.webp",
      "/images/kasol/stay/30.webp",
      "/images/kasol/stay/4.webp",
      "/images/kasol/stay/5.webp",
      "/images/kasol/stay/6.webp",
      "/images/kasol/stay/7.webp",
      "/images/kasol/stay/8.webp",
      "/images/kasol/stay/9.webp",
    ],
  },
  {
    tags: "bir",
    images: [
      "/images/bir/stay/1.webp",
      "/images/bir/stay/10.webp",
      "/images/bir/stay/11.webp",
      "/images/bir/stay/12.webp",
      "/images/bir/stay/13.webp",
      "/images/bir/stay/14.webp",
      "/images/bir/stay/2.webp",
      "/images/bir/stay/3.webp",
      "/images/bir/stay/4.webp",
      "/images/bir/stay/5.webp",
      "/images/bir/stay/6.webp",
      "/images/bir/stay/7.webp",
      "/images/bir/stay/8.webp",
      "/images/bir/stay/9.webp",
    ],
  },
];
